app = "my-flask-backend"

[build]
  dockerfile = "Dockerfile"

[[services]]
  http_checks = []
  internal_port = 5000

  [[services.http]]
    services = ["http"]
    [[services.http.ports]]
      port = "80"
      handlers = ["http"]
